In [25]:
import torch

In [26]:
torch.__version__

'1.4.0'

In [27]:
torch.cuda.is_available()

False

In [28]:
d = [[1,2,3],
    [2,3,4],
    [4,5,6]]

In [29]:
t = torch.tensor(d)
t

tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

In [30]:
print type(t)

print t.shape

<class 'torch.Tensor'>
torch.Size([3, 3])


In [31]:
t.reshape(1,9)

tensor([[1, 2, 3, 2, 3, 4, 4, 5, 6]])

In [32]:
print t.dtype
print t.device

torch.int64
cpu


In [33]:
import numpy as np
n = np.array([1,2,3])

te = torch.tensor(n)
te2 = torch.Tensor(n) #uses the global default dtype (float32)

print torch.get_default_dtype()

#the following to still keep the reference to the original numpy array. Hence if the array changes, the tensor changes as well. 
#this is faster, since there is no copying of data. 
te3 = torch.as_tensor(n)
te4 = torch.from_numpy(n)

print te2
print te
print te3
print te4

#best methods out of these :  te and te3. te3 - accepts any python array structure. te4 supports only numpy. 

torch.float32
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [34]:
torch.eye(3) #i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [35]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [36]:
torch.ones(3)

tensor([1., 1., 1.])

In [37]:
torch.rand(4)

tensor([0.3627, 0.5565, 0.9572, 0.3985])

In [40]:
### Rank, Axes and Shape

# Rank - basically number of elements in t.shape. Or the number of axes needed to obtain an element. 

torch.tensor(t.shape).prod()

t.numel() #function to get the number of elements.



9

In [39]:
#### Flatten, Reshape and Squeeze

In [47]:
reshape = t.reshape(1,9)

In [48]:
sq = reshape.squeeze() #squeeze removes all axes with length 1. Unsqueeze adds axes with length 1. 

In [79]:
print sq.unsqueeze(dim=1)
print sq.unsqueeze(dim=1).shape
print sq.unsqueeze(dim=-1).shape
print sq.unsqueeze(dim=-2).shape

tensor([[1],
        [2],
        [3],
        [2],
        [3],
        [4],
        [4],
        [5],
        [6]])
torch.Size([9, 1])
torch.Size([9, 1])
torch.Size([1, 9])


In [68]:
#flatten : Basically reduce the whole tensor to one flag list/one dimensional tensor/ tensor with rank 1. 
def flatten(t) :
    print t.reshape(-1) #first impl 
    
    s = t.reshape(1,-1) #-1 asks pytorch to infer the dimen value. 
    print s.squeeze()
    
flatten(t)
    

tensor([1, 2, 3, 2, 3, 4, 4, 5, 6])
tensor([1, 2, 3, 2, 3, 4, 4, 5, 6])


In [84]:
## cat() 
t1 = torch.tensor([[1,2,3],
             [3,4,5],
             [6,7,8]])

t2 = torch.tensor([[1,4,3],
             [3,6,5],
             [6,8,8]])

print torch.cat((t1,t2), dim=1) 
print torch.cat((t1,t2), dim=0)

tensor([[1, 2, 3, 1, 4, 3],
        [3, 4, 5, 3, 6, 5],
        [6, 7, 8, 6, 8, 8]])
tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8],
        [1, 4, 3],
        [3, 6, 5],
        [6, 8, 8]])
