In [2]:
import torch

In [3]:
torch.__version__

'1.4.0'

In [7]:
torch.cuda.is_available()

False

In [5]:
d = [[1,2,3],
    [2,3,4],
    [4,5,6]]

In [6]:
t = torch.tensor(d)
t

tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

In [7]:
print type(t)

print t.shape

<class 'torch.Tensor'>
torch.Size([3, 3])


In [8]:
t.reshape(1,9)

tensor([[1, 2, 3, 2, 3, 4, 4, 5, 6]])

In [9]:
print t.dtype
print t.device

torch.int64
cpu


In [24]:
import numpy as np
n = np.array([1,2,3])

te = torch.tensor(n)
te2 = torch.Tensor(n) #uses the global default dtype (float32)

print torch.get_default_dtype()

#the following to still keep the reference to the original numpy array. Hence if the array changes, the tensor changes as well. 
#this is faster, since there is no copying of data. 
te3 = torch.as_tensor(n)
te4 = torch.from_numpy(n)

print te2
print te
print te3
print te4

#best methods out of these :  te and te3. te3 - accepts any python array structure. te4 supports only numpy. 

torch.float32
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [17]:
torch.eye(3) #i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [20]:
torch.ones(3)

tensor([1., 1., 1.])

In [22]:
torch.rand(4)

tensor([0.8106, 0.7297, 0.3071, 0.6276])