In [1]:
import torch

In [2]:
torch.__version__

'1.4.0'

In [3]:
torch.cuda.is_available()

False

In [4]:
d = [[1,2,3],
    [2,3,4],
    [4,5,6]]

In [5]:
t = torch.tensor(d)
t

tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

In [6]:
print type(t)

print t.shape

<class 'torch.Tensor'>
torch.Size([3, 3])


In [7]:
t.reshape(1,9)

tensor([[1, 2, 3, 2, 3, 4, 4, 5, 6]])

In [8]:
print t.dtype
print t.device

torch.int64
cpu


In [9]:
import numpy as np
n = np.array([1,2,3])

te = torch.tensor(n)
te2 = torch.Tensor(n) #uses the global default dtype (float32)

print torch.get_default_dtype()

#the following to still keep the reference to the original numpy array. Hence if the array changes, the tensor changes as well. 
#this is faster, since there is no copying of data. 
te3 = torch.as_tensor(n)
te4 = torch.from_numpy(n)

print te2
print te
print te3
print te4

#best methods out of these :  te and te3. te3 - accepts any python array structure. te4 supports only numpy. 

torch.float32
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [10]:
torch.eye(3) #i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [12]:
torch.ones(3)

tensor([1., 1., 1.])

In [13]:
torch.rand(4)

tensor([0.2465, 0.7449, 0.1582, 0.3816])

In [14]:
### Rank, Axes and Shape

# Rank - basically number of elements in t.shape. Or the number of axes needed to obtain an element. 

torch.tensor(t.shape).prod()

t.numel() #function to get the number of elements.



9

In [15]:
#### Flatten, Reshape and Squeeze

In [16]:
reshape = t.reshape(1,9)

In [17]:
sq = reshape.squeeze() #squeeze removes all axes with length 1. Unsqueeze adds axes with length 1. 

In [18]:
print sq.unsqueeze(dim=1)
print sq.unsqueeze(dim=1).shape
print sq.unsqueeze(dim=-1).shape
print sq.unsqueeze(dim=-2).shape

tensor([[1],
        [2],
        [3],
        [2],
        [3],
        [4],
        [4],
        [5],
        [6]])
torch.Size([9, 1])
torch.Size([9, 1])
torch.Size([1, 9])


In [19]:
#flatten : Basically reduce the whole tensor to one flag list/one dimensional tensor/ tensor with rank 1. 
def flatten(t) :
    print t.reshape(-1) #first impl 
    
    s = t.reshape(1,-1) #-1 asks pytorch to infer the dimen value. 
    print s.squeeze()
    
flatten(t)
    

tensor([1, 2, 3, 2, 3, 4, 4, 5, 6])
tensor([1, 2, 3, 2, 3, 4, 4, 5, 6])


In [20]:
## cat() 
t1 = torch.tensor([[1,2,3],
             [3,4,5],
             [6,7,8]])

t2 = torch.tensor([[1,4,3],
             [3,6,5],
             [6,8,8]])

print torch.cat((t1,t2), dim=1) 
print torch.cat((t1,t2), dim=0)

tensor([[1, 2, 3, 1, 4, 3],
        [3, 4, 5, 3, 6, 5],
        [6, 7, 8, 6, 8, 8]])
tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8],
        [1, 4, 3],
        [3, 6, 5],
        [6, 8, 8]])


In [22]:
##Element-wise operations and Broadcasting. 


t1+t2

tensor([[ 2,  6,  6],
        [ 6, 10, 10],
        [12, 15, 16]])

In [23]:
t1*t2 #corresponding elements will be multiplied, not matrix multiplicaiton.

tensor([[ 1,  8,  9],
        [ 9, 24, 25],
        [36, 56, 64]])

In [24]:
t1 * 2  # Here the scalar is broadcasted (copy axes) and then multiplied element-wise.

tensor([[ 2,  4,  6],
        [ 6,  8, 10],
        [12, 14, 16]])

In [25]:
t3 = torch.tensor(np.broadcast_to(7,t1.shape))

In [26]:
t3

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

In [29]:
print t2 
t4 = torch.tensor([1,3,4])
print t4
t4 + t2 #broadcasting in torch

tensor([[1, 4, 3],
        [3, 6, 5],
        [6, 8, 8]])
tensor([1, 3, 4])


tensor([[ 2,  7,  7],
        [ 4,  9,  9],
        [ 7, 11, 12]])

In [30]:
##Reduction Tensor Ops and argmax

In [31]:
#Any operation that reduces number of elements in a tensor. Ex : sum() operation reduces numel to 1

In [66]:
t5 = torch.tensor([[1,4,5,6],
                   [2,3,4,5],
                   [3,4,6,5],
                   [1,5,6,7]],dtype=float)

In [67]:
t5.sum(dim=0)    #summing all elements of first axis.

tensor([ 7., 16., 21., 23.], dtype=torch.float64)

In [68]:
t5.max()

tensor(7., dtype=torch.float64)

In [69]:
t5.argmax() #returns the index of the max element in the flattened tensor. 

tensor(15)

In [70]:
t5.max(dim=0) #vertically

torch.return_types.max(
values=tensor([3., 5., 6., 7.], dtype=torch.float64),
indices=tensor([2, 3, 3, 3]))

In [71]:
t5.max(dim=1) #horizontal

torch.return_types.max(
values=tensor([6., 5., 6., 7.], dtype=torch.float64),
indices=tensor([3, 3, 2, 3]))

In [74]:
print t5.mean(dim=1).tolist()
print t5.mean(dim=1).numpy()

[4.0, 3.5, 4.5, 4.75]
[4.   3.5  4.5  4.75]


In [ ]:
t5.dtype